export const ROUTE = {
  DASHBOARD: "/dashboard",
  LOGIN: "/auth/login",
  REGISTER: "/auth/register",
  SNACKS: "/snacks",
  SNACKS_FORM: "/snacks/form",
  SNACKS_DETAIL: "/snacks/detail",
  USERS: "/users",
  USERS_FORM: "/users/form",
  USERS_DETAIL: "/users/detail",
  ROLES: "/roles",
  ROLES_FORM: "/roles/form",
  ROLES_DETAIL: "/roles/detail",
  MOVIE: "/movie",
  MOVIE_DETAIL: "/movie/detail",
  MOVIE_FORM: "/movie/form",
  STUDIO: "/studio",
  STUDIO_DETAIL: "/studio/detail",
  STUDIO_FORM: "/studio/form",
  SCHEDULE: "/schedule",
  SCHEDULE_DETAIL: "/schedule/detail",
  SCHEDULE_FORM: "/schedule/form",
};
